"""
compute_ap_small.py — AP_small Evaluation for All Ablation Experiments
=======================================================================
Automatically runs predictions for every experiment, converts to COCO
format, runs COCOeval, and extracts AP_small / AP_medium / AP_large.

All results are saved to:
    runs/experiments/ap_small_results.csv

Usage (from project root):
    # Run all experiments:
    CUDA_VISIBLE_DEVICES="" python scripts/compute_ap_small.py

    # Run a single experiment by name (resumes/appends to CSV):
    CUDA_VISIBLE_DEVICES="" python scripts/compute_ap_small.py kd_combined_p3_dominant

    # Run multiple specific experiments:
    CUDA_VISIBLE_DEVICES="" python scripts/compute_ap_small.py Teacher kd_combined Baseline

CUDA_VISIBLE_DEVICES="" forces CPU-only mode and avoids GPU OOM entirely.

Requirements:
    pip install pycocotools
"""

import os
import sys
import json
import csv
import glob

# Force CPU — must be set before any CUDA initialisation
os.environ.setdefault("CUDA_VISIBLE_DEVICES", "")

import gc
import torch
from ultralytics import YOLO
from pycocotools.coco import COCO
from pycocotools.cocoeval import COCOeval

# ==============================================================================
#  CONFIGURATION
# ==============================================================================

BASE_DIR  = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TEST_IMGS = os.path.join(BASE_DIR, "datasets", "HRIPCB", "test", "images")

# Ground truth COCO JSON and image-id map (generated by yolo_to_coco.py)
GT_JSON      = os.path.join(BASE_DIR, "data", "coco_annotations.json")
IMG_ID_MAP   = os.path.join(BASE_DIR, "data", "image_id_map.json")

RESULTS_CSV  = os.path.join(BASE_DIR, "runs", "experiments", "ap_small_results.csv")

DEVICE     = "cpu"   # CPU avoids GPU OOM when evaluating multiple models sequentially
IMAGE_SIZE = 640

# ==============================================================================
#  EXPERIMENTS — weights path and display name for each experiment
# ==============================================================================

EXPERIMENTS = [
    ("Teacher (yolov8m)",  "runs/experiments/teacher/yolov8m/weights/best.pt"),
    ("Baseline (yolov8n)", "runs/experiments/baseline/yolov8n/weights/best.pt"),
    ("kd_logit_only",      "runs/experiments/kd/kd_logit_only/weights/best.pt"),
    ("kd_logit_strong",    "runs/experiments/kd/kd_logit_strong/weights/best.pt"),
    ("kd_feat_only",       "runs/experiments/kd/kd_feat_only4/weights/best.pt"),
    ("kd_combined",        "runs/experiments/kd/kd_combined/weights/best.pt"),
    ("kd_box",             "runs/experiments/kd/kd_box/weights/best.pt"),
    #("kd_combined_full",   "runs/experiments/kd/kd_combined_full/weights/best.pt"),
    ("scratch_baseline",   "runs/experiments/kd/scratch_baseline/weights/best.pt"),
    ("scratch_kd_combined","runs/experiments/kd/scratch_kd_combined/weights/best.pt"),
    ("kd_combined_p3_heavy","runs/experiments/kd/kd_combined_p3_heavy/weights/best.pt"),
    ("kd_combined_p3_dominant","runs/experiments/kd/kd_combined_p3_dominant/weights/best.pt"),

]


# ==============================================================================
#  STEP 1: Run predictions and convert to COCO format in memory
# ==============================================================================

def predict_to_coco(weights_path: str, image_id_map: dict) -> list:
    """
    Run model.predict() on all test images and return COCO-format predictions.

    Args:
        weights_path  : path to .pt checkpoint
        image_id_map  : dict mapping filename → image_id (from image_id_map.json)

    Returns:
        list of dicts: [{image_id, category_id, bbox:[x,y,w,h], score}, ...]
    """
    model = YOLO(weights_path)
    image_files = sorted(glob.glob(os.path.join(TEST_IMGS, "*.jpg")) +
                         glob.glob(os.path.join(TEST_IMGS, "*.jpeg")) +
                         glob.glob(os.path.join(TEST_IMGS, "*.png")))

    coco_preds = []

    try:
        # Process truly one image at a time — minimises peak RAM for large models
        for img_path in image_files:
            img_name = os.path.basename(img_path)
            if img_name not in image_id_map:
                continue
            image_id = image_id_map[img_name]

            results = model.predict(
                source=img_path,
                imgsz=IMAGE_SIZE,
                device=DEVICE,
                conf=0.001,
                iou=0.6,
                verbose=False,
                save=False,
                save_txt=False,
            )
            result = results[0]

            if result.boxes is None or len(result.boxes) == 0:
                del results, result
                gc.collect()
                continue

            boxes = result.boxes.xyxy.cpu().numpy()
            confs = result.boxes.conf.cpu().numpy()
            clses = result.boxes.cls.cpu().numpy()

            for (x1, y1, x2, y2), conf, cls in zip(boxes, confs, clses):
                bw = float(x2 - x1)
                bh = float(y2 - y1)
                coco_preds.append({
                    "image_id"   : image_id,
                    "category_id": int(cls),
                    "bbox"       : [float(x1), float(y1), bw, bh],
                    "score"      : float(conf),
                })

            del results, result
            gc.collect()

    finally:
        # Always free GPU memory — even if an exception occurs mid-inference
        del model
        gc.collect()
        torch.cuda.empty_cache()

    return coco_preds


# ==============================================================================
#  STEP 2: Run COCOeval and extract all AP metrics
# ==============================================================================

def run_cocoeval(gt_json_path: str, coco_preds: list) -> dict:
    """
    Run COCOeval on predictions and return all AP metrics.

    Returns dict with keys:
        AP, AP50, AP75, AP_small, AP_medium, AP_large,
        AR1, AR10, AR100, AR_small, AR_medium, AR_large
    """
    coco_gt = COCO(gt_json_path)

    if not coco_preds:
        print("  [WARNING] No predictions — returning zeros.")
        return {k: 0.0 for k in ["AP", "AP50", "AP75", "AP_small", "AP_medium", "AP_large"]}

    coco_dt = coco_gt.loadRes(coco_preds)

    coco_eval = COCOeval(coco_gt, coco_dt, "bbox")
    coco_eval.evaluate()
    coco_eval.accumulate()
    coco_eval.summarize()

    # COCOeval.stats order:
    # 0: AP @[0.50:0.95]
    # 1: AP @0.50
    # 2: AP @0.75
    # 3: AP_small  @[0.50:0.95]  area < 32²
    # 4: AP_medium @[0.50:0.95]  32² < area < 96²
    # 5: AP_large  @[0.50:0.95]  area > 96²
    # 6: AR @maxDets=1
    # 7: AR @maxDets=10
    # 8: AR @maxDets=100
    # 9: AR_small
    # 10: AR_medium
    # 11: AR_large
    stats = coco_eval.stats

    return {
        "AP"        : round(float(stats[0]), 4),
        "AP50"      : round(float(stats[1]), 4),
        "AP75"      : round(float(stats[2]), 4),
        "AP_small"  : round(float(stats[3]), 4),
        "AP_medium" : round(float(stats[4]), 4),
        "AP_large"  : round(float(stats[5]), 4),
        "AR_small"  : round(float(stats[9]),  4),
        "AR_medium" : round(float(stats[10]), 4),
        "AR_large"  : round(float(stats[11]), 4),
    }


# ==============================================================================
#  STEP 3: Print summary table
# ==============================================================================

def print_table(all_results: list):
    print("\n" + "=" * 90)
    print("  AP_small Results — All Ablation Experiments")
    print("=" * 90)
    print(f"  {'Experiment':<22} {'AP':>7} {'AP50':>7} {'AP75':>7} {'AP_small':>9} {'AP_med':>8} {'AP_large':>9}")
    print("  " + "-" * 75)

    baseline_ap_small = None
    for name, metrics in all_results:
        if "baseline" in name.lower() and baseline_ap_small is None:
            baseline_ap_small = metrics["AP_small"]

        delta = ""
        if baseline_ap_small is not None and "baseline" not in name.lower() and "teacher" not in name.lower():
            diff = metrics["AP_small"] - baseline_ap_small
            delta = f"  ({'+' if diff >= 0 else ''}{diff:.4f})"

        print(
            f"  {name:<22} "
            f"{metrics['AP']:>7.4f} "
            f"{metrics['AP50']:>7.4f} "
            f"{metrics['AP75']:>7.4f} "
            f"{metrics['AP_small']:>9.4f} "
            f"{metrics['AP_medium']:>8.4f} "
            f"{metrics['AP_large']:>9.4f}"
            f"{delta}"
        )

    print("=" * 90)
    print("  delta = AP_small change vs baseline\n")


# ==============================================================================
#  MAIN
# ==============================================================================

def load_existing_csv() -> dict:
    """Load already-completed experiments from CSV so we can skip/resume."""
    done = {}
    if not os.path.isfile(RESULTS_CSV):
        return done
    with open(RESULTS_CSV, newline="") as f:
        reader = csv.DictReader(f)
        for row in reader:
            done[row["experiment"]] = {k: float(v) for k, v in row.items() if k != "experiment"}
    return done


def append_to_csv(name: str, metrics: dict, write_header: bool):
    os.makedirs(os.path.dirname(RESULTS_CSV), exist_ok=True)
    with open(RESULTS_CSV, "a", newline="") as f:
        writer = csv.writer(f)
        if write_header:
            writer.writerow(["experiment", "AP", "AP50", "AP75",
                             "AP_small", "AP_medium", "AP_large",
                             "AR_small", "AR_medium", "AR_large"])
        writer.writerow([
            name,
            metrics["AP"], metrics["AP50"], metrics["AP75"],
            metrics["AP_small"], metrics["AP_medium"], metrics["AP_large"],
            metrics["AR_small"], metrics["AR_medium"], metrics["AR_large"],
        ])


def main():
    gc.collect()

    # Optional: run only specific experiments passed as CLI args
    # e.g.  python scripts/compute_ap_small.py kd_combined Teacher
    filter_names = [a.lower() for a in sys.argv[1:]]

    # Validate required files
    for path, label in [(GT_JSON, "coco_annotations.json"), (IMG_ID_MAP, "image_id_map.json")]:
        if not os.path.isfile(path):
            print(f"[ERROR] {label} not found at: {path}")
            print("  Run scripts/yolo_to_coco.py first to generate it.")
            sys.exit(1)

    if not os.path.isdir(TEST_IMGS):
        print(f"[ERROR] Test images directory not found: {TEST_IMGS}")
        sys.exit(1)

    with open(IMG_ID_MAP) as f:
        image_id_map = json.load(f)

    # Load already-done experiments to allow resuming
    done = load_existing_csv()
    csv_is_new = not os.path.isfile(RESULTS_CSV)

    all_results = list(done.items())   # start from already-completed entries

    for exp_name, weights_rel in EXPERIMENTS:
        # Filter by CLI arg if provided
        if filter_names and not any(f in exp_name.lower() for f in filter_names):
            continue

        # Skip if already evaluated (resume mode)
        if exp_name in done and not filter_names:
            print(f"\n[SKIP] {exp_name} — already in CSV, skipping.")
            continue

        weights_path = os.path.join(BASE_DIR, weights_rel)
        if not os.path.isfile(weights_path):
            print(f"\n[SKIP] {exp_name} — weights not found: {weights_path}")
            continue

        print(f"\n{'='*65}")
        print(f"  Evaluating: {exp_name}")
        print(f"  Weights   : {weights_path}")
        print(f"{'='*65}")

        try:
            coco_preds = predict_to_coco(weights_path, image_id_map)
            print(f"  Predictions generated: {len(coco_preds)}")

            metrics = run_cocoeval(GT_JSON, coco_preds)
            all_results.append((exp_name, metrics))

            # Write immediately — so a crash mid-run doesn't lose progress
            append_to_csv(exp_name, metrics, write_header=csv_is_new)
            csv_is_new = False

            print(f"  AP_small  : {metrics['AP_small']:.4f}")
            print(f"  AP_medium : {metrics['AP_medium']:.4f}")
            print(f"  AP_large  : {metrics['AP_large']:.4f}")

        except Exception as e:
            print(f"  [ERROR] Failed for {exp_name}: {e}")
            continue

    if not all_results:
        print("\n[ERROR] No experiments could be evaluated.")
        sys.exit(1)

    print_table(all_results)
    print(f"  Results saved to: {RESULTS_CSV}")


if __name__ == "__main__":
    main()
